### ISSUE TITLE
Create the pub/sub mechanisms (RabbitMQ)

### ISSUE THREAD

**Issue by minreiseah** [minreiseah/orbital#4]

**Comment by chengjunyuan** [comment]
I've figured out how to publish messages, but I have no idea how to receive messages. Am using the `amqprs` crate for Rust.

**Comment by chengjunyuan** [comment]
Update: I figured it out. Use `basic_get` instead of `basic_consume`, and keep asking ChatGPT. The `lapin` crate on Rust is much older and ChatGPT knows how to use it, thankfully `amqprs` is basically a carbon copy of `lapin` in terms of functionality (but it promises to be faster, whatever that means), so asking ChatGPT how to do things with `lapin` provides a very helpful quickstart if you don't want to read a million pages of documentation for AMPQ systems.
